ServerResourcePacks:
    Gondor: http://www.mcmiddleearth.com/content/Gondor.zip
    Eriador: http://www.mcmiddleearth.com/content/Eriador.zip
    Lothlorien: http://www.mcmiddleearth.com/content/Lothlorien.zip
    Rohan: http://www.mcmiddleearth.com/content/Rohan.zip
    Mordor: http://www.mcmiddleearth.com/content/Mordor.zip
    Dwarf: http://www.mcmiddleearth.com/content/Moria.zip