ServerResourcePacks:
    Gondor: https://www.dropbox.com/s/uauumtajvj7l9na/Gondor%20new%20wc.zip?dl=1
    Eriador: http://build.mcmiddleearth.com/content/Eriador.zip
    Lothlorien: http://build.mcmiddleearth.com/content/Lothlorien.zip
    Rohan: http://build.mcmiddleearth.com/content/Rohan.zip
    Mordor: http://build.mcmiddleearth.com/content/Mordor.zip
    Dwarf: http://build.mcmiddleearth.com/content/Moria.zip