ServerResourcePacks:
    Gondor: http://build.mcmiddleearth.com/content/Gondor2.zip
    Eriador: http://build.mcmiddleearth.com/content/Eriador.zip
    Lothlorien: http://build.mcmiddleearth.com/content/Lothlorien.zip
    Rohan: http://build.mcmiddleearth.com/content/Rohan.zip
    Mordor: http://build.mcmiddleearth.com/content/Mordor.zip
    Dwarf: http://build.mcmiddleearth.com/content/Moria.zip